{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Admission Duration Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(sum by (instance, operation, type) (apiserver_admission_controller_admission_duration_seconds_sum)[1h:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Example 123",
   "type": "timeseries",
   "description": "This plot does this and that",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "idelta(etcd_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Rate > 0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate((sum by (instance, pod) (kubelet_container_log_filesystem_used_bytes) != 0)[1h:1m]) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "ceph_osd_commit_latency_ms", "legendFormat": "__auto" }
   ]
  }
 ]
}