{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Log Rate > 0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate((sum by (instance, pod) (kubelet_container_log_filesystem_used_bytes) != 0)[1h:1m]) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Example 123",
   "type": "timeseries",
   "description": "This plot does this and that",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "irate(sum by (instance, device) (node_network_transmit_bytes_total)[1h:5m]) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Admission Duration Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "rate(sum by (instance, operation, type) (apiserver_admission_controller_admission_duration_seconds_sum)[1h:])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}